name: "export"
on:
  workflow_dispatch:
  push:
    paths:
      - "**.gd"
      - "**.tscn"
      - "**.import"
      - "**.tres"
      - "**.ttf"
      - ".github/workflows/export.yml"
      - "export_presets.cfg"
    branches:
      - main

jobs:
  export:
    uses: bend-n/godot-actions/.github/workflows/callable-export.yml@main
    with:
      export-name: 2048
      image: ghcr.io/bend-n/godot-2d:4.1.1
      platforms: "windows linux web android mac"
